### ISSUE TITLE
Support for TR-OCR Base Printed for AWS Neuron(Inferentia) 

### ISSUE THREAD

**Issue by umanniyaz** [aws-neuron/aws-neuron-samples#3]
Please provide support for Tr-OCR Base Printed conversion using Neuron and its inference in jit trace ,
getting this error when trying through the uploaded notebook, the process flow is as below
after meeting tensor shape as 768, encoder complies but decoder fails to compile with neuron command -9
@hyandell  @mattmcclean  @aws-maens  @brunopistone 

 
![image](https://user-images.githubusercontent.com/33204214/211843833-ac383a78-0e47-43ad-88dd-ee21b086b9f0.png)

![image](https://user-images.githubusercontent.com/33204214/211843942-9e1ce0e7-d3db-4ca6-860a-6dbc747608c9.png)

![image](https://user-images.githubusercontent.com/33204214/211844120-2e06df6b-e413-4be3-bf34-6f10d31f7387.png)

![image](https://user-images.githubusercontent.com/33204214/211843722-a2164b39-bc35-4492-9515-2067b8b6059c.png)

**Comment by awsilya** [comment]
Hi @umanniyaz I opened a ticket with our team.  Will update you when we have more information.  
Thank you.

**Comment by aws-rishyraj** [comment]
Hi @umanniyaz, I've looked into the issue and I've determined that it's a size mismatch issue with the decoder when passing in the `last_hidden_states` from the encoder. To fix this, please change the size of `encoder_hidden_states` to `torch.rand([1,577,768])`.

If you want to experiment with other sized VisionEncoderDecoder models I suggest checking the input and output sizes of the models. This can be verified by running the non-traced model and checking the shape with `.shape`. 

Hope this helps!

**Comment by aws-rishyraj** [comment]
@umanniyaz I've reopened the issue, so I can verify that the proposed fix works on your end.

**Comment by aws-taylor** [comment]
Hello @umanniyaz,

 We haven't heard from you in a while, so I'm going to go ahead and resolve this. Please feel free to re-open if the proposed fix does not work for you.

-T
