### ISSUE TITLE
TypeError: Got unsupported ScalarType BFloat16

### ISSUE THREAD

**Issue by eric80116** [aws-neuron/aws-neuron-samples#33]
When running the "Compile the model into an optimized TorchScript and save the TorchScript" step on the torch-neuronx/inference/hf_pretrained_sd2_512_inference.ipynb and got the error of "**Got unsupported ScalarType BFloat16**"

**Comment by jeffhataws** [comment]
Hi @eric80116, thanks for filing the issue. This is a known issue. Will you try the solution in https://github.com/aws-neuron/aws-neuron-samples/issues/31 ?

**Comment by eric80116** [comment]
Fixed it. Thanks
