### ISSUE TITLE
Clearer instructions on how to get models from Hugging Face

### ISSUE THREAD

**Issue by massi-ang** [aws-neuron/aws-neuron-samples#37]
It would be useful to add some information about how to obtain the models from Hugging Face and in particular:
- use git clone <repo>
- install LFS extension for git

**Comment by aws-rhsoln** [comment]
Thank you for reporting the issue. You can use the getting started guide here:  https://huggingface.co/docs/hub/repositories-getting-started  to download HF models. Closing this issue, in case there is an issue still, please re-open.

**Comment by aws-donkrets** [comment]
Hi [massi-ang](https://github.com/massi-ang) - hope that [aws-rhsoln](https://github.com/aws-rhsoln) suggestion and provided link helped to resolve your issue. Closing this one out since its been open for 3 months. If you need further help, please open a new ticket.

**Comment by massi-ang** [comment]
The point was that such instructions, or link to instructions, should be part of your notebooks

**Comment by aws-donkrets** [comment]
Thx for clarifying - I'm keeping an internal ticket open to track the future notebook change.
