### ISSUE TITLE
Shell script variables confuse devices and cores

### ISSUE THREAD

**Issue by ajayvohra2005** [aws-neuron/aws-neuron-samples#43]
Samples shell scripts' variables confuse devices and cores. A `Trn1` instances has 16 Neuron Devices (chips), each with 2 cores.  

This sample [script](https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/training/tp_dp_gpt_neox_hf_pretrain/tp_dp_gpt_neox_20b_hf_pretrain/tp_dp_gpt_neox_20b_hf_pretrain.sh), on Line 31 shows:
 
```export NEURON_NUM_DEVICES=32```
 
I think, the correct code would be:
 
```export NEURON_NUM_CORES=32```
 
 
The [deprecated Neuron Megatron example](https://github.com/aws-neuron/aws-neuron-reference-for-megatron-lm/blob/master/examples/pretrain_gpt3_5B_24layers_bf16_bs1024_slurm.sh) script shows it correctly:
 
NUM_NEURONCORES=32

**Comment by aws-rhsoln** [comment]
Thank you for reporting the issue. Apologies for the confusion with the variable. We will change the variable name to NUM_NEURONCORES=32. However, one thing to note, that variable is used only in that shell script and can be named to anything.
