### ISSUE TITLE
Deploy meta-llama-2-13b-sampling.ipynb on inf2.24xlarge 

### ISSUE THREAD

**Issue by rajamdhi** [aws-neuron/aws-neuron-samples#50]
Hi, 

Is it possible to deploy meta-llama-2-13b-sampling.ipynb on inf2.24xlarge machine?.

**Comment by aws-taylor** [comment]
Hello @rajamdhi,

  Thank you for your issue. Take a look at the related issue https://github.com/aws-neuron/aws-neuron-sdk/issues/741. In short - yes - it should be possible to use an inf2.24xlarge as long as you configure your context length appropriately.
  
Regards,
Taylor

**Comment by mrnikwaws** [comment]
Closing since we have not had any further questions on this topic
