### ISSUE TITLE
Decoder fails to compile the MarianMT example notebook

### ISSUE THREAD

**Issue by rykcode** [aws-neuron/aws-neuron-samples#6]
I am trying to compile the MarianMT language translation model for `Inf1` instance.

```
kernel version = 5.4.228-131.415.amzn2.x86_64
Instance type on which the compilation was attempted = Inf1.2xlarge, Amazon Linux 2 AMI, 
```
Following is my `pip freeze` output
```
# pip freeze
torch==1.7.1
torch-neuron==1.7.1.2.5.8.0
transformers==4.0.1
tensorflow==1.15.5
sentencepiece==0.1.97
absl-py==1.4.0
astor==0.8.1
attrs==22.2.0
certifi==2022.12.7
charset-normalizer==3.0.1
click==8.1.3
decorator==5.1.1
dmlc-nnvm==1.13.0.0+0
dmlc-topi==1.13.0.0+0
dmlc-tvm==1.13.0.0+0
exceptiongroup==1.1.0
filelock==3.9.0
gast==0.2.2
google-pasta==0.2.0
grpcio==1.51.1
h5py==2.10.0
idna==3.4
importlib-metadata==6.0.0
inferentia-hwm==1.13.0.0+0
iniconfig==2.0.0
islpy==2021.1+aws2021.x.80.0.bld0
joblib==1.2.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
Markdown==3.4.1
MarkupSafe==2.1.2
networkx==2.5
neuron-cc==1.13.5.0+7dcf000a6
numpy==1.18.5
opt-einsum==3.3.0
packaging==23.0
Pillow==9.4.0
pluggy==1.0.0
protobuf==3.20.1
pytest==7.2.1
regex==2022.10.31
requests==2.28.2
sacremoses==0.0.53
scipy==1.4.1
six==1.16.0
tensorboard==1.15.0
tensorflow-estimator==1.15.1
termcolor==2.2.0
tokenizers==0.9.4
tomli==2.0.1
tqdm==4.64.1
typing_extensions==4.5.0
urllib3==1.26.14
Werkzeug==2.2.3
wrapt==1.14.1
zipp==3.13.0
```
I followed this link for
[PyTorch installation].(https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuron/setup/pytorch-install.html)
Then I followed the instructions in 
[this notebook](https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuron/inference/marianmt/MarianMT.ipynb)
I get the following compilation error

[aws neuron bug report compilation error.txt](https://github.com/aws-neuron/aws-neuron-samples/files/10757445/aws.neuron.bug.report.compilation.error.txt)

**Comment by aws-mvaria** [comment]
Hello, we are working on updating the tutorial content which should address the issue you are seeing. We will update you as soon as the content is available.

**Comment by mrnikwaws** [comment]
Hi @rykcode,

This fix went out in a previous release, so closing this ticket
