### ISSUE TITLE
Is it possible to run YoloV8 on Neuron?

### ISSUE THREAD

**Issue by nithrous** [aws-neuron/aws-neuron-samples#75]
There are examples how to use yolov5-7. Does Neuron support yolov8?

**Comment by jeffhataws** [comment]
Hi @nithrous. Thanks for reaching out. We have not tested YoloV8 on Neuron. Please go ahead and give it a try and let us know if you run into any issue.

**Comment by aws-donkrets** [comment]
Hi @nithrous. Closing this ticket for now. If you encounter any difficulty running Yolo8  please open a new ticket.
