### ISSUE TITLE
Request for backwards compatibility with older tensorflow (2.4.0 - 2.7.0) versions. I am unable to trace a calamari OCR model.

### ISSUE THREAD

**Issue by ParasSharmaIISL** [aws-neuron/aws-neuron-samples#78]
The calamari model is trained on tensorflow 2.7.0 which utilises tfaip library and the lowest tensorflow_neuron version 2.7.4 uses a higher keras version. Due to this version mismatch I am unable to load my (calamari-ocr) keras model to the python environment with tensorflow-neuron and not able to trace the model. If I save this model in a tensorflow saved model, the traced model's computation graph only works on CPU and not inferntia chips. This is the repository "https://github.com/Calamari-OCR/calamari".

**Comment by aws-rhsoln** [comment]
Thank you for reporting the issue. To unblock the issue, loading the saved model into the inference script might be a good idea. Can you elaborate a bit more on what you mean by not working on inferentia chips? Is there a compiler error or an execution failure?

**Comment by aws-taylor** [comment]
Hello @ParasSharmaIISL,

 We haven't heard from you in a while, so I'm going to go ahead an resolve this issue. If you still need this support, @aws-rhsoln had a few questions that may help us help you better.

**Comment by paras692** [comment]
> Thank you for reporting the issue. To unblock the issue, loading the saved model into the inference script might be a good idea. Can you elaborate a bit more on what you mean by not working on inferentia chips? Is there a compiler error or an execution failure?

Hi @aws-rhsoln , the calamari OCR library uses tfaip library which is built upon tensorflow, so all the model's convelutional layers are condensed into a single layer, which makes it unable to be converted to AWS inf2 gpu layer and is running on CPU in an inf2 server.
