### ISSUE TITLE
Running Multiple Models on Different NeuronCores

### ISSUE THREAD

**Issue by kocabiyik** [aws-neuron/aws-neuron-samples#84]
Thank you for providing various samples. I have a specific question regarding the setup for running multiple models.

**Context**:
- I have two models: `ModelA` and `ModelB`.
- I want to run inference on both models to obtain outputs: `OutputA` and `OutputB`.
- After obtaining the outputs, I plan to concatenate `OutputA` and `OutputB` and feed them into a third model, `ModelC`.

**Questions**:
1. Can I run `ModelA` and `ModelB` on different NeuronCores in parallel? If so, how can I specify a NeuronCore?
2. Is this setup ideal for achieving low latency?

FYI: I plan to experiment using an `inf1` instance.

**Comment by mrnikwaws** [comment]
Neuron cores are bound at the process level, and you can control which cores are passed using these environment variables: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/perf/neuron-cc/parallel-ncgs.html

> Is this setup ideal for achieving low latency?

Achieving the lowest model latency is highly model dependent - there is no one size fits all recipe, but certainly if you can save switching a given core from switching between models that will help.

**Comment by mrnikwaws** [comment]
Closing this ticket since I think the question was answered.  Please re-open if you need further assistance.
